from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, ConversationViewSet, MessageViewSet

# Create a router and register our viewsets
router = DefaultRouter()
router.register(r"users", UserViewSet, basename="users")
router.register(r"conversations", ConversationViewSet, basename="conversations")
router.register(r"messages", MessageViewSet, basename="messages")

# The API URLs are now determined automatically by the router
urlpatterns = [
    path("api/v1/", include(router.urls)),
    # Additional REST framework URLs for authentication
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

# URL patterns generated by the router:
#
# Users:
# - GET /api/v1/users/ - List all users
# - POST /api/v1/users/ - Create a new user
# - GET /api/v1/users/{user_id}/ - Retrieve a specific user
# - PUT /api/v1/users/{user_id}/ - Update a specific user
# - PATCH /api/v1/users/{user_id}/ - Partially update a specific user
# - DELETE /api/v1/users/{user_id}/ - Delete a specific user
# - POST /api/v1/users/{user_id}/set_online_status/ - Set user online status
#
# Conversations:
# - GET /api/v1/conversations/ - List all conversations (for authenticated user)
# - POST /api/v1/conversations/ - Create a new conversation
# - GET /api/v1/conversations/{conversation_id}/ - Retrieve a specific conversation
# - PUT /api/v1/conversations/{conversation_id}/ - Update a specific conversation
# - PATCH /api/v1/conversations/{conversation_id}/ - Partially update a specific conversation
# - DELETE /api/v1/conversations/{conversation_id}/ - Delete a specific conversation
# - POST /api/v1/conversations/{conversation_id}/add_participant/ - Add participant to conversation
# - POST /api/v1/conversations/{conversation_id}/remove_participant/ - Remove participant from conversation
# - GET /api/v1/conversations/{conversation_id}/messages/ - Get all messages in conversation
#
# Messages:
# - GET /api/v1/messages/ - List all messages (for authenticated user)
# - POST /api/v1/messages/ - Create a new message
# - GET /api/v1/messages/{message_id}/ - Retrieve a specific message
# - PUT /api/v1/messages/{message_id}/ - Update a specific message
# - PATCH /api/v1/messages/{message_id}/ - Partially update a specific message
# - DELETE /api/v1/messages/{message_id}/ - Delete a specific message
# - GET /api/v1/messages/my_messages/ - Get all messages sent by current user
# - GET /api/v1/messages/{message_id}/conversation_messages/ - Get all messages from same conversation
