from django.urls import path, include
from rest_framework import routers
from rest_framework_nested import routers as nested_routers
from .views import UserViewSet, ConversationViewSet, MessageViewSet

# Create a router and register our viewsets with DefaultRouter()
router = routers.DefaultRouter()
router.register(r"users", UserViewSet, basename="users")
router.register(r"conversations", ConversationViewSet, basename="conversations")
router.register(r"messages", MessageViewSet, basename="messages")

# Create a nested router for messages within conversations using NestedDefaultRouter
conversation_router = nested_routers.NestedDefaultRouter(
    router, r"conversations", lookup="conversation"
)
conversation_router.register(
    r"messages", MessageViewSet, basename="conversation-messages"
)

# The API URLs are now determined automatically by the router
urlpatterns = [
    path("", include(router.urls)),
    path("", include(conversation_router.urls)),
]

# URL patterns generated by the router:
#
# Users:
# - GET /api/users/ - List all users
# - POST /api/users/ - Create a new user
# - GET /api/users/{user_id}/ - Retrieve a specific user
# - PUT /api/users/{user_id}/ - Update a specific user
# - PATCH /api/users/{user_id}/ - Partially update a specific user
# - DELETE /api/users/{user_id}/ - Delete a specific user
# - POST /api/users/{user_id}/set_online_status/ - Set user online status
#
# Conversations:
# - GET /api/conversations/ - List all conversations (for authenticated user)
# - POST /api/conversations/ - Create a new conversation
# - GET /api/conversations/{conversation_id}/ - Retrieve a specific conversation
# - PUT /api/conversations/{conversation_id}/ - Update a specific conversation
# - PATCH /api/conversations/{conversation_id}/ - Partially update a specific conversation
# - DELETE /api/conversations/{conversation_id}/ - Delete a specific conversation
# - POST /api/conversations/{conversation_id}/add_participant/ - Add participant to conversation
# - POST /api/conversations/{conversation_id}/remove_participant/ - Remove participant from conversation
# - GET /api/conversations/{conversation_id}/messages/ - Get all messages in conversation
#
# Messages (standalone):
# - GET /api/messages/ - List all messages (for authenticated user)
# - POST /api/messages/ - Create a new message
# - GET /api/messages/{message_id}/ - Retrieve a specific message
# - PUT /api/messages/{message_id}/ - Update a specific message
# - PATCH /api/messages/{message_id}/ - Partially update a specific message
# - DELETE /api/messages/{message_id}/ - Delete a specific message
# - GET /api/messages/my_messages/ - Get all messages sent by current user
# - GET /api/messages/{message_id}/conversation_messages/ - Get all messages from same conversation
#
# Nested Messages (within conversations using NestedDefaultRouter):
# - GET /api/conversations/{conversation_id}/messages/ - List messages in specific conversation
# - POST /api/conversations/{conversation_id}/messages/ - Create message in specific conversation
# - GET /api/conversations/{conversation_id}/messages/{message_id}/ - Get specific message in conversation
# - PUT /api/conversations/{conversation_id}/messages/{message_id}/ - Update message in conversation
# - PATCH /api/conversations/{conversation_id}/messages/{message_id}/ - Partial update message in conversation
# - DELETE /api/conversations/{conversation_id}/messages/{message_id}/ - Delete message in conversation
