# Generated by Django 5.2.1 on 2025-06-15 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the message has been edited'),
        ),
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False, help_text='Whether the message has been edited'),
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_content', models.TextField(help_text='Previous content before edit')),
                ('new_content', models.TextField(help_text='New content after edit')),
                ('edit_reason', models.CharField(blank=True, help_text='Optional reason for the edit', max_length=255, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True, help_text='When the edit was made')),
                ('edited_by', models.ForeignKey(help_text='User who made the edit', on_delete=django.db.models.deletion.CASCADE, related_name='message_edits', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(help_text='Message this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='messaging.message')),
            ],
            options={
                'verbose_name': 'Message Edit History',
                'verbose_name_plural': 'Message Edit Histories',
                'db_table': 'messaging_message_history',
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['message', '-edited_at'], name='messaging_m_message_959a22_idx'), models.Index(fields=['edited_by', '-edited_at'], name='messaging_m_edited__4cfed0_idx')],
            },
        ),
    ]
