# Generated by Django 5.2.1 on 2025-06-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_edit_count_message_edited_messagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('edit', 'Message Edit'), ('system', 'System Notification')], default='message', help_text='Type of notification', max_length=20),
        ),
    ]
