# Generated by Django 5.2.1 on 2025-06-15 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_parent_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read', '-timestamp'], name='messaging_m_receive_e1ef65_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='messaging_m_is_read_019d68_idx'),
        ),
    ]
