apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: ClusterIP
  selector:
    # This selector now points to any pod with the 'app: django' label,
    # regardless of its version. This is ideal for rolling updates.
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 