# Generated by Django 5.2.1 on 2025-06-01 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_convers_38b855_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_sender__7375e3_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the message was sent'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-sent_at'], name='messages_convers_1401f8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-sent_at'], name='messages_sender__a8857b_idx'),
        ),
    ]
